# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qsOtSk25y70A_LK3e5E93_Z43jfzndhX
"""

import requests

page = requests.get("https://www.flowverse.co/projects")
page

from bs4 import BeautifulSoup
soup = BeautifulSoup(page.content, 'html.parser')

list(soup.children)

[type(item) for item in list(soup.children)]

html = list(soup.children)[2]
list(html.children)

len(list(html.children))

body = list(html.children)[1]
list(body.children)

p = list(body.children)[1]
p.get_text()

soup = BeautifulSoup(page.content, 'html.parser')

item_list = soup.find_all('div', class_="collection-item-dapps w-dyn-item w-col w-col-4")

len(item_list)

"""<h1 class="blog-title-home">"""

print(item_list)

type(item_list)

name_set_w_tag = soup.find_all('h1', class_ = 'blog-title-home')
print(name_set_w_tag)

name_set = []
for item in name_set_w_tag:
  name_set.append(item.string)
print(name_set)
print(name_set)

print(name_set)
print(name_set[218])

set(name_set)
len(name_set)